"""Polarimetric science layer: double differencing, Stokes cube production,
radial Stokes, and the Mueller matrix model interface."""

from .stokes import (
    CRITICAL_ANGLES,
    azimuthal_angle,
    aperture_polarization,
    build_stokes_cube,
    build_stokes_cubes,
    double_difference,
    median_stokes_cube,
    polarization_products,
    radial_stokes,
    rotate_qu,
    normalized_single_difference,
    single_difference,
)
from .products import ProductWriter
from .mueller import (
    MuellerMatrixModel,
    apply_mueller_model,
    build_corrected_stokes_cube,
    fit_empirical_cycle_correction,
)
from .instpol import (
    InstrumentalPolarization,
    fit_ip_uphi,
    fit_ip_uphi_all,
    mean_ip,
    subtract_ip,
)
from .fast_axis import (
    OFFSET_TO_FRAME,
    ApertureCycles,
    FastAxisResult,
    PolStdResult,
    PreparedCycle,
    butterfly_phase,
    combine_at_offset,
    curve_of_growth_polarization,
    fit_fast_axis_butterfly,
    fit_theta_off_polstd,
    measure_cycles,
    prepare_cycles,
    scan_fast_axis_offset_butterfly,
    wrap_offset,
)
from .standards import PolarizedStandard, serkowski_p

__all__ = [
    "ApertureCycles",
    "CRITICAL_ANGLES",
    "FastAxisResult",
    "InstrumentalPolarization",
    "MuellerMatrixModel",
    "OFFSET_TO_FRAME",
    "PolStdResult",
    "PolarizedStandard",
    "PreparedCycle",
    "ProductWriter",
    "aperture_polarization",
    "apply_mueller_model",
    "azimuthal_angle",
    "build_corrected_stokes_cube",
    "build_stokes_cube",
    "build_stokes_cubes",
    "butterfly_phase",
    "combine_at_offset",
    "curve_of_growth_polarization",
    "double_difference",
    "fit_empirical_cycle_correction",
    "fit_fast_axis_butterfly",
    "fit_ip_uphi",
    "fit_ip_uphi_all",
    "fit_theta_off_polstd",
    "mean_ip",
    "measure_cycles",
    "median_stokes_cube",
    "normalized_single_difference",
    "polarization_products",
    "prepare_cycles",
    "radial_stokes",
    "rotate_qu",
    "scan_fast_axis_offset_butterfly",
    "serkowski_p",
    "single_difference",
    "subtract_ip",
    "wrap_offset",
]
