"""Science reduction layer, instrument-agnostic: master darks/flats/skies,
frame calibration, sky subtraction, and image registration. Instrument
specifics come in through ``instruments``; low-level helpers live in
``utils``."""

from .masters import (
    make_master_darks,
    make_master_flats,
    make_master_masks,
    make_master_skies,
    make_masters,
    make_flats,
    flat_sort_key,
    required_flat_type_for,
    split_polarimetric_flats,
)
from .calibrate import (
    find_closest_dark,
    find_closest_flat,
    find_closest_sky,
    find_matching_master,
    interpolate_bad_pixels,
    local_interpolate_bad_pixels,
    local_median_replace_bad_pixels,
    reduce_frame,
)
from .sky import (
    subtract_annulus_background,
    subtract_background,
    subtract_dither_background,
    subtract_dither_pairs,
    subtract_mean_background,
    subtract_sky_frames,
)
from .registration import (
    center_frame,
    center_frames,
    derotate_frames,
    find_center,
    align_beams,
    find_center_centroid,
    find_center_crosscorr,
    find_center_silhouette,
    find_center_symmetry,
    find_center_wings,
    find_center_gaussian,
    find_center_max,
    find_center_min,
    find_center_quantile_peak,
    find_center_smooth,
    fit_2d_gaussian,
    measure_beam_offset,
    median_combine,
    register_beam_stack,
    register_frames_to_template,
)

# The public API. Without it ``from reduction import *`` also binds the
# submodule names (masters, calibrate, sky, registration, defaults), and the
# keylists in ``defaults`` stay reachable as ``reduction.defaults`` where
# they belong -- they are configuration, not API.
__all__ = [
    "center_frame",
    "center_frames",
    "derotate_frames",
    "find_center",
    "find_center_centroid",
    "find_center_crosscorr",
    "find_center_gaussian",
    "find_center_max",
    "find_center_min",
    "find_center_quantile_peak",
    "find_center_silhouette",
    "find_center_smooth",
    "find_center_symmetry",
    "find_center_wings",
    "find_closest_dark",
    "find_closest_flat",
    "find_closest_sky",
    "find_matching_master",
    "fit_2d_gaussian",
    "align_beams",
    "flat_sort_key",
    "interpolate_bad_pixels",
    "local_interpolate_bad_pixels",
    "local_median_replace_bad_pixels",
    "make_flats",
    "make_master_darks",
    "make_master_flats",
    "make_master_masks",
    "make_master_skies",
    "make_masters",
    "measure_beam_offset",
    "median_combine",
    "reduce_frame",
    "register_beam_stack",
    "register_frames_to_template",
    "required_flat_type_for",
    "split_polarimetric_flats",
    "subtract_annulus_background",
    "subtract_background",
    "subtract_dither_background",
    "subtract_dither_pairs",
    "subtract_mean_background",
    "subtract_sky_frames",
]
